### ISSUE TITLE
Bug "Invalid configuration setting: verbose"

### ISSUE THREAD

**Issue by fonsecas72** [mamuz/PhpDependencyAnalysis#14]
Hi, I have introduced a bug in your library.
When you call the analyze command in verbose mode, e.g. "bin/phpda analyze phpda.yml.dist -v"
The following exception is throw
```
  [InvalidArgumentException]              
  Invalid configuration setting: verbose 
```
This happens because we are passing all the input to the Config class.
Before trying to fix it I wanted to know what do you think.

**Comment by mamuz** [comment]
I suggest to remove the implementation of [PR11](https://github.com/mamuz/PhpDependencyAnalysis/pull/11).

The effort to fix this issue compared to the value of [PR11](https://github.com/mamuz/PhpDependencyAnalysis/pull/11) is to high.

I also think that would make it more future proof.

**Comment by fonsecas72** [comment]
I agree. 
Also: I think we should definitely protect our selves from this issue in the future.
