### ISSUE TITLE
Use a single file as the source

### ISSUE THREAD

**Issue by fonsecas72** [mamuz/PhpDependencyAnalysis#15]
Hi, I see that this library can only accept directories as the source. I can see that this makes sense.
What do you think of also accept single files?
Sometimes I have files with such an amount of dependencies that I'm only to understand its dependencies individually.

Another way of solving it: Could we possible generate multiple svgs in such situations?
I mean, could we optionally generate a svg(target) for each file?

I know this may sound odd, but what do you think of it?

**Comment by marius-rizac** [comment]
You can check only one file with this settings:

```yml
source: './src/AppBundle/Command'
filePattern: 'ImportAllCommand.php'
```
will check only one file.

I would make phpda to work with parameters passed. Like I want to check only one file, I pass it as a parameter. Configuration file should be something generic accepted, a convention like `.phpda.yml` in the root directory

**Comment by mamuz** [comment]
@marius-rizac :+1:
