### ISSUE TITLE
namespaceFilter plugin is never called

### ISSUE THREAD

**Issue by phpsurf** [mamuz/PhpDependencyAnalysis#18]
Custom filter plugin, implementing NamespaceFilterInterface interface, declared in yml as namespaceFilter option and added to composer autoload.
The plugin class is well loaded, but the filter method is never called.

**Comment by mamuz** [comment]
Hi @phpsurf,

for me its not reproducable. Maybe you can give me more details, such as the used configuration.
You can also try to add a test for this issue.

**Comment by phpsurf** [comment]
Hi, thanks for your reply. This is now resolved, I actually figured out that the filter plugin only gets called when there is an excludePattern defined in the visitorOptions. Sorry if I missed this in the doc, or maybe something to add to it. Maybe still some unwanted behaviour to fix. Thanks

**Comment by mamuz** [comment]
Sideeffeft regarding "excludePattern" is not reproducable.
