### ISSUE TITLE
Add a PHAR

### ISSUE THREAD

**Issue by theofidry** [mamuz/PhpDependencyAnalysis#23]
First thanks for this lib, it's great! But would it be possible to have a PHAR file with a self-update command to use it? Installing the lib via Composer is not always possible, especially for this kind of library depending on specific version of `phpdocumentor/reflection-docblock` and `nikic/php-parser`.

**Comment by mamuz** [comment]
Definitely a very good idea. I will introduce it.

**Comment by tobiasoberrauch** [comment]
https://github.com/mamuz/PhpDependencyAnalysis/pull/25
(without self-update)

**Comment by mamuz** [comment]
Released with https://github.com/mamuz/PhpDependencyAnalysis/releases/tag/v1.3.0

**Comment by mamuz** [comment]
Released with https://github.com/mamuz/PhpDependencyAnalysis/releases/tag/v1.3.0
