### ISSUE TITLE
@see tag is interpreted wrong

### ISSUE THREAD

**Issue by temp** [mamuz/PhpDependencyAnalysis#29]
I'm getting this warning on an analyzer-run:
```
Warning	"\Some\Namespace\Here\https://www.hipchat.com/docs/apiv2/method/get_room" is 
not a valid Fqsen. on line 75 ./src/some/namespace/here/Class.php
```
From the referenced api-doc:
```
/**
 * @see https://www.hipchat.com/docs/apiv2/method/get_room
 */
```
Looking at https://www.phpdoc.org/docs/latest/references/phpdoc/tags/see.html, the @see tag can either take a FQSEN, or an URI, which is wrongly interpreted here.

**Comment by mamuz** [comment]
Will be solved with https://github.com/phpDocumentor/ReflectionDocBlock/pull/88

**Comment by hoshomoh** [comment]
Any update on this issue. Seems its not resolved yet.

**Comment by mamuz** [comment]
will be fixed with next major
