### ISSUE TITLE
Return proper Status Code after running command

### ISSUE THREAD

**Issue by mjacobus** [mamuz/PhpDependencyAnalysis#4]
Hey Marco!

It would be cool if phpda returned a proper code when it finds violations. If it returns 1 (or any nonzero) it could be used in the building process. The build would fail if any violation is found.

I think [here](http://symfony.com/doc/current/components/console/introduction.html#calling-an-existing-command) you can find an exemple on how to manipulate the return code.

Cheers!

**Comment by mamuz** [comment]
@mjacobus 

..great idea! Thanks for the issue.
