### ISSUE TITLE
Packagist still on v1.3.1 - can you update it, or setup auto update

### ISSUE THREAD

**Issue by lsv** [mamuz/PhpDependencyAnalysis#45]
My Environment (version of the project, operating system, or hardware)

```
...replace me...
```

My `phpda.yml`:

```json
...replace me...
```

When I run this command:

```
...replace me...
```

Actual behavior:

```
...replace me...
```

Expected behavior:

```
...replace me...
```

**Comment by dallgoot** [comment]
Hi, i second that : requirements are out of synchro between : 
**Github**
https://github.com/mamuz/PhpDependencyAnalysis/blob/master/composer.json
**Packagist**
https://packagist.org/packages/mamuz/php-dependency-analysis#dev-master

Note that i don't know how the 'auto-update" mentionned by @lsv works so i can not help :/

**Comment by mamuz** [comment]
Thanks for hint. I juat need to refresh webhook token for that. Now automated integration is working again.

@dallgoot https://packagist.org/about explains how "Auto-Update" works.
