### ISSUE TITLE
Composer dependency versions

### ISSUE THREAD

**Issue by tmilos** [mamuz/PhpDependencyAnalysis#5]
Hello,
This is a great tool. Nice work. 
Noticed that in your ``composer.json`` you have quite strong version specs like ``symfony/console: 2.6.*``. Haven't tried though, but think it won't work if my project is on other symfony version, 2.3, 2.5 or 2.7. Guess then I could not add your tool to my composer.json, but would have to have a separate installation for it, and that would complicate plugin maintenance. Could you consider loosening a bit on your dependencies and use ``~`` version spec so the tool can be added to app require-dev w/out dependency conflicts?

**Comment by mamuz** [comment]
Hi @tmilos ,
thanks for your feedback and thanks for your valuable hint. You are right and i changed and released it with https://github.com/mamuz/PhpDependencyAnalysis/releases/tag/v0.5.1.

**Comment by garex** [comment]
Still not usable with sf 3.0 ))

**Comment by mamuz** [comment]
@garex :+1:

**Comment by mamuz** [comment]
Fixed with [Release v0.6.1](https://github.com/mamuz/PhpDependencyAnalysis/releases/tag/v0.6.1)
